development:
  adapter: postgresql
  encoding: unicode
  database: Peek_challenge_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: Peek_challenge_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Peek_challenge_production
  pool: 5

cucumber:
  <<: *test